### ISSUE TITLE
Text under the colored boxes in the manual not correctly centered

### ISSUE THREAD

**Issue by quark67** [Rmano/xkcdcolors#1]
This can better be seen if in `xkcdcolors-manual.tex` you replace the line 24:
```latex
        \node[align=center, anchor=north west, text width=\ancho] at (0,0) {\strut\hspace{0pt}\relax #1};
```

by:
```latex
        \node[fill=lightgray, align=center, anchor=north west, text width=\ancho] at (0,0) {\strut\hspace{0pt}\relax #1};
```

(`fill=lightgray` is added in options of `\node`).

As you see below, the color names are centered in the light gray boxes, but the light gray boxes are larger than the colored boxes, so the color names are not centered under the colored boxes 
![image](https://user-images.githubusercontent.com/9338576/67531482-26b59200-f6c3-11e9-894b-c4377b7b984a.png)

If you see carefully, clearly length A is greater than length B:
![image](https://user-images.githubusercontent.com/9338576/67531931-cf182600-f6c4-11e9-81a3-dddfd1a891d5.png)

This offset is due to the `inner xsep`, which is by default `0.3333em` (in **pgfmanual**, section 17.2.3).

So I suggest using:

```latex
        \node[fill=lightgray, inner xsep=0pt, align=center, anchor=north west, text width=\ancho] at (0,0) {\strut\hspace{0pt}\relax #1};
```

in line 24, which give this result:
![image](https://user-images.githubusercontent.com/9338576/67532213-be1be480-f6c5-11e9-89e1-d6ea0dab0e6e.png)

So centering is OK, but not spacing between colors. This can be corrected by replacing line 1012:

```latex
{\colorblock{\xkcdcol}\ }
```

by

```latex
{\colorblock{\xkcdcol}\hspace{0.6666em}\ }
```

(because left inner sep is 0.3333em and right inner sep is 0.3333em.)

So you obtain:
![image](https://user-images.githubusercontent.com/9338576/67532415-6e89e880-f6c6-11e9-8712-6ddc44335036.png)

Finally, you can remove `fill=lightgray` in line 24.

**Comment by Rmano** [comment]
Yes, you're quite right. I'll fix it (unless you prefer making a PR).
Congrats for issue #1! 

Thanks

**Comment by quark67** [comment]
You can fix it, no problem.
